# Generated by Django 4.2.4 on 2023-08-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='company',
        ),
    ]
