# Generated by Django 4.2.4 on 2023-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_table_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
