# Generated by Django 4.2.4 on 2023-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
    ]
