# Generated by Django 4.2.4 on 2023-08-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dishID', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Order ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='dish_images')),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Order ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready to pickup', 'Ready to Pickup'), ('delivered', 'Delivered')], default='received', max_length=50)),
                ('dishes', models.ManyToManyField(blank=True, related_name='Orders', to='zomcrud.dishes')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
